<?php
/**
 * Tamil OTT Releases - Configuration File
 *
 * Keep your API keys and configuration parameters here.
 * This file should never be exposed to the public browser.
 */

// Timezone configuration (used for weekend date calculation)
if (!defined('APP_TIMEZONE')) {
    define('APP_TIMEZONE', 'America/New_York');
}
date_default_timezone_set(APP_TIMEZONE);



// API keys live in secrets.php (gitignored; generated by the deploy workflow in production).
if (is_file(__DIR__ . '/secrets.php')) {
    require_once __DIR__ . '/secrets.php';
}

// Cache duration in seconds (6 hours = 6 * 3600 = 21600 seconds)
define('CACHE_DURATION', 21600);

// Default region for streaming availability (India)
define('DEFAULT_REGION', 'IN');

// Target language filter (ta = Tamil ISO 639-1)
define('TARGET_LANGUAGE', 'ta');

// Path to cache directory
define('CACHE_DIR', __DIR__ . '/cache');

// Whether to show demo mock data when no API key is configured or when API is in demo mode
define('ENABLE_DEMO_FALLBACK', true);

// Disable all caching when running locally (localhost / 127.0.0.1 / php -S), so changes show instantly.
if (!defined('DISABLE_CACHE')) {
    $host = strtolower(explode(':', $_SERVER['HTTP_HOST'] ?? '')[0]);
    define('DISABLE_CACHE', in_array($host, ['localhost', '127.0.0.1', '[::1]'], true) || str_ends_with($host, '.local') || str_ends_with($host, '.test'));
}
